### PR TITLE
add kerning toggle (-k)

### PR DESCRIPTION
**Pull request by frankrolf**
addresses #6

### CODE REVIEW

**Comment by frankrolf** [comment]
I implemented your suggestion @benkiel, if you have time to check out the result I’d be grateful :-)

**Comment by frankrolf** [comment]
Did you get a moment to review this @benkiel, or should I just merge it?

**Comment by benkiel** [comment]
Yes, this works well! I would suggest that the toggle be `-nk`, as `-k` implies that kerning is on, but the nice output note on the pdf helps here

**Review by benkiel — APPROVED** [review]

**Comment by frankrolf** [comment]
Thanks for taking a look!

I understand that the single-letter options may be ambiguous, however this also makes it possible to chain them.

For when you need to be explicit, there’s always the `-kerning_off` option:
https://github.com/adobe-type-tools/drawBotProofing/blob/main/textProof.py#L110

**Pull request merged**
